# Generated by Django 3.1.3 on 2022-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(default='N/A'),
        ),
    ]
